### ISSUE TITLE
fatal error: Unable to locate credentials

### ISSUE THREAD

**Issue by Denys-Bushulyak** [remyleone/scw-s3-action#1]
- name: Configure AWS Credentials
        uses: remyleone/scw-s3-action@v0.0.1
        with:
          args: s3 rm --recursive s3://some.some/folder
        env:
          SCW_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SCW_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SCW_REGION: fr-par

**Comment by matthprost** [comment]
Hello @Denys-Bushulyak,

Could you try to upgrade your version using v0.0.2 like: `remyleone/scw-s3-action@v0.0.2`.

Also note that this error occur because your credentials are not set. Maybe you should double check your secrets `AWS_ACCESS_KEY_ID` & `AWS_ACCESS_KEY_ID` names and values into GitHub secrets of your repository.
